#pragma once

#define WD_LSI_FREQUENCY_HZ 40 * 1000
#define WD_PRESCALER_DIVIDER_BASE 4
#define WD_PRESCALER_BITS 3
#define WD_PRESCALER WD_PRESCALER_DIVIDER_BASE << WD_PRESCALER_BITS
#define WD_PERIOD_BASE_MS ((int)(WD_LSI_FREQUENCY_HZ) / (WD_PRESCALER))
#define WD_PERIOD_MS 3 * 1000
#define WD_PERIOD WD_PERIOD_BASE_MS * (WD_PERIOD_MS / 1000)
#define WD_RESET_INTERVAL_MS 1 * 1000

void wdTask(void *pvParameters __attribute__((unused)));
