#pragma once

#define DISPLAY_PANEL_CMD_INVERSION_SWAP
#define DISPLAY_PANEL_COLOR_RGB 0b00000000
#define DISPLAY_PANEL_COLOR_BGR 0b00001000
#define DISPLAY_PANEL_COLOR DISPLAY_PANEL_COLOR_BGR

#define DISPLAY_ROTATION_NORMAL 0b00000000
#define DISPLAY_ROTATION_90_CW 0b01110000
#define DISPLAY_ROTATION_180 0b11010000
#define DISPLAY_ROTATION_90_CCW 0b10110000
#define DISPLAY_ROTATION DISPLAY_ROTATION_90_CCW
#define DISPLAY_NORMAL_WIDTH 128
#define DISPLAY_NORMAL_HEIGHT 160
#define DISPLAY_MEMORY_NORMAL_WIDTH 128
#define DISPLAY_MEMORY_NORMAL_HEIGHT 160
#define DISPLAY_MEMORY_NORMAL_OFFSET_X 0
#define DISPLAY_MEMORY_NORMAL_OFFSET_Y 0

#if DISPLAY_ROTATION == DISPLAY_ROTATION_NORMAL
	#define DISPLAY_WIDTH DISPLAY_NORMAL_WIDTH
	#define DISPLAY_HEIGHT DISPLAY_NORMAL_HEIGHT
	#define DISPLAY_MEMORY_WIDTH DISPLAY_MEMORY_NORMAL_WIDTH
	#define DISPLAY_MEMORY_HEIGHT DISPLAY_MEMORY_NORMAL_HEIGHT
	#define DISPLAY_MEMORY_OFFSET_X DISPLAY_MEMORY_NORMAL_OFFSET_X
	#define DISPLAY_MEMORY_OFFSET_Y DISPLAY_MEMORY_NORMAL_OFFSET_Y
#elif DISPLAY_ROTATION == DISPLAY_ROTATION_90_CW
	#define DISPLAY_WIDTH DISPLAY_NORMAL_HEIGHT
	#define DISPLAY_HEIGHT DISPLAY_NORMAL_WIDTH
	#define DISPLAY_MEMORY_WIDTH DISPLAY_MEMORY_NORMAL_HEIGHT
	#define DISPLAY_MEMORY_HEIGHT DISPLAY_MEMORY_NORMAL_WIDTH
	#define DISPLAY_MEMORY_OFFSET_X DISPLAY_MEMORY_NORMAL_OFFSET_Y
	#define DISPLAY_MEMORY_OFFSET_Y DISPLAY_MEMORY_NORMAL_OFFSET_X
#elif DISPLAY_ROTATION == DISPLAY_ROTATION_90_CCW
	#define DISPLAY_WIDTH DISPLAY_NORMAL_HEIGHT
	#define DISPLAY_HEIGHT DISPLAY_NORMAL_WIDTH
	#define DISPLAY_MEMORY_WIDTH DISPLAY_MEMORY_NORMAL_HEIGHT
	#define DISPLAY_MEMORY_HEIGHT DISPLAY_MEMORY_NORMAL_WIDTH
	#define DISPLAY_MEMORY_OFFSET_X 0
	#define DISPLAY_MEMORY_OFFSET_Y DISPLAY_MEMORY_NORMAL_OFFSET_X
#elif DISPLAY_ROTATION == DISPLAY_ROTATION_180
	#define DISPLAY_WIDTH DISPLAY_NORMAL_WIDTH
	#define DISPLAY_HEIGHT DISPLAY_NORMAL_HEIGHT
	#define DISPLAY_MEMORY_WIDTH DISPLAY_MEMORY_NORMAL_WIDTH
	#define DISPLAY_MEMORY_HEIGHT DISPLAY_MEMORY_NORMAL_HEIGHT
	#define DISPLAY_MEMORY_OFFSET_X DISPLAY_MEMORY_NORMAL_OFFSET_X
	#define DISPLAY_MEMORY_OFFSET_Y 0
#endif

#define DISPLAY_COLOR_DEPTH_12 0x03
#define DISPLAY_COLOR_DEPTH_16 0x05
#define DISPLAY_COLOR_DEPTH_18 0x06
#define DISPLAY_COLOR_DEPTH DISPLAY_COLOR_DEPTH_16
#if DISPLAY_COLOR_DEPTH == DISPLAY_COLOR_DEPTH_12
	#define DISPLAY_BITS_PER_PIXEL 12
	#define DISPLAY_COMPLETE_TRANSFER_NUM_PIXELS 2
	#define DISPLAY_DMA_CCR_MSIZE DMA_CCR_MSIZE_8BIT
	#define DISPLAY_DMA_MSIZE 8
	#define DISPLAY_DMA_CCR_PSIZE DMA_CCR_PSIZE_8BIT
	#define DISPLAY_DMA_PSIZE DISPLAY_DMA_MSIZE
#elif DISPLAY_COLOR_DEPTH == DISPLAY_COLOR_DEPTH_16
	#define DISPLAY_BITS_PER_PIXEL 16
	#define DISPLAY_COMPLETE_TRANSFER_NUM_PIXELS 1
	#define DISPLAY_DMA_CCR_MSIZE DMA_CCR_MSIZE_16BIT
	#define DISPLAY_DMA_MSIZE 16
	#define DISPLAY_DMA_CCR_PSIZE DMA_CCR_PSIZE_16BIT
	#define DISPLAY_DMA_PSIZE DISPLAY_DMA_MSIZE
#elif DISPLAY_COLOR_DEPTH == DISPLAY_COLOR_DEPTH_18
	#define DISPLAY_BITS_PER_PIXEL 18
	#define DISPLAY_COMPLETE_TRANSFER_NUM_PIXELS 3
	#define DISPLAY_DMA_CCR_MSIZE DMA_CCR_MSIZE_8BIT
	#define DISPLAY_DMA_MSIZE 8
	#define DISPLAY_DMA_CCR_PSIZE DMA_CCR_PSIZE_8BIT
	#define DISPLAY_DMA_PSIZE DISPLAY_DMA_MSIZE
#endif

#define DISPLAY_DMA_BOUNDARY UINT16_MAX
#define DISPLAY_RESET_DELAY_US 100

#define DISPLAY_CMD_NOP 0x00
#define DISPLAY_CMD_SOFT_RESET 0x01
#define DISPLAY_CMD_SLEEP_OUT 0x11
#define DISPLAY_CMD_NORMAL_DISPLAY 0x13
#ifdef DISPLAY_PANEL_CMD_INVERSION_SWAP
	#define DISPLAY_CMD_INVERSION_ON 0x21 /* some displays it is the other way... */
	#define DISPLAY_CMD_INVERSION_OFF 0x20 /* ... around despite the datasheet */
#else
	#define DISPLAY_CMD_INVERSION_ON 0x20
	#define DISPLAY_CMD_INVERSION_OFF 0x21
#endif

#define DISPLAY_CMD_IDLE_MODE_OFF 0x38
#define DISPLAY_CMD_PIXEL_COLOR_CODING 0x3a
#define DISPLAY_CMD_MEMORY_ACCESS_CONTROL 0x36
#define DISPLAY_CMD_DISPLAY_PANEL_ON 0x29
#define DISPLAY_CMD_COLUMN_ADDRESS_SET 0x2a
#define DISPLAY_CMD_ROW_ADDRESS_SET 0x2b
#define DISPLAY_CMD_WRITE_MEMORY_START 0x2c
#define DISPLAY_CMD_WRITE_MEMORY_CONTINUE 0x3c

typedef struct {
	struct {
		uint8_t greenFirst :4;
		uint8_t redFirst :4;
		uint8_t redSecond :4;
		uint8_t blueFirst :4;
		uint8_t blueSecond :4;
		uint8_t greenSecond :4;
	};
	uint8_t start;
	uint8_t middle;
	uint8_t tail;
} pixel12Bit_t;

typedef struct {
	struct {
		uint8_t red :5;
		uint8_t green :6;
		uint8_t blue :5;
	};
	uint16_t rgbPixel;
} pixel16Bit_t;

typedef struct {
	struct {
		uint8_t red :6;
		uint8_t :2;
		uint8_t green :6;
		uint8_t	:2;
		uint8_t blue :6;
		uint8_t :2;
	};
	uint8_t redPixel;
	uint8_t greenPixel;
	uint8_t bluePixel;
} pixel18Bit_t;

void sendBufferToQueue(displayBuffer_t *p_buf);
